import {
  Sparkles,
  Fish,
  Accessibility,
  Scale,
  Plane,
  Flag,
  Globe,
  Gift,
  SirenIcon,
  User,
  Users,
  Coins,
  FolderLock,
  CalendarCheck,
  TrendingUp,
  BarChart3,
  ClipboardList,
  FileWarning,
  FileText,
  Megaphone,
  RefreshCw,
  Search,
  KeyRound,
  Lock,
  Radar,
  Truck,
  ShieldAlert,
  Ban,
  ShieldCheck,
  Handshake,
  Brain,
  FlaskConical,
  Armchair,
  IdCard,
  type LucideIcon,
} from "lucide-react"

const EMOJI_ICON_MAP: Record<string, LucideIcon> = {
  "♻️": RefreshCw,
  "♿": Accessibility,
  "⚖️": Scale,
  "✈️": Plane,
  "🇪🇺": Flag,
  "🌐": Globe,
  "🎁": Gift,
  "🎣": Fish,
  "🏃": SirenIcon,
  "👤": User,
  "👥": Users,
  "💰": Coins,
  "📁": FolderLock,
  "📅": CalendarCheck,
  "📈": TrendingUp,
  "📊": BarChart3,
  "📋": ClipboardList,
  "📑": FileWarning,
  "📝": FileText,
  "📢": Megaphone,
  "🔄": RefreshCw,
  "🔍": Search,
  "🔑": KeyRound,
  "🔒": Lock,
  "🕵️": Radar,
  "🚛": Truck,
  "🚨": ShieldAlert,
  "🚫": Ban,
  "🛡️": ShieldCheck,
  "🤝": Handshake,
  "🧠": Brain,
  "🧪": FlaskConical,
  "🪑": Armchair,
  "🪪": IdCard,
}

export function getLearningOutcomeIcon(icon?: string): LucideIcon {
  if (!icon) return Sparkles
  return EMOJI_ICON_MAP[icon] || Sparkles
}
